export const FEATURE_FLAGS_LIST_REQUEST = 'FEATURE_FLAGS_LIST_REQUEST'
export const FEATURE_FLAGS_LIST_SUCCESS = 'FEATURE_FLAGS_LIST_SUCCESS'
export const FEATURE_FLAGS_LIST_FAIL = 'FEATURE_FLAGS_LIST_FAIL'
export const FEATURE_FLAG_LIST_UPDATE_ITEM = 'FEATURE_FLAG_LIST_UPDATE_ITEM'

export const FEATURE_FLAG_UPDATE_STATUS_REQUEST = 'FEATURE_FLAG_UPDATE_STATUS_REQUEST'
export const FEATURE_FLAG_UPDATE_STATUS_SUCCESS = 'FEATURE_FLAG_UPDATE_STATUS_SUCCESS'
export const FEATURE_FLAG_UPDATE_STATUS_FAIL = 'FEATURE_FLAG_UPDATE_STATUS_FAIL'
export const FEATURE_FLAG_UPDATE_STATUS_RESET = 'FEATURE_FLAG_UPDATE_STATUS_RESET'

export const FEATURE_FLAG_UPDATE_TRAFFIC_REQUEST = 'FEATURE_FLAG_UPDATE_TRAFFIC_REQUEST'
export const FEATURE_FLAG_UPDATE_TRAFFIC_SUCCESS = 'FEATURE_FLAG_UPDATE_TRAFFIC_SUCCESS'
export const FEATURE_FLAG_UPDATE_TRAFFIC_FAIL = 'FEATURE_FLAG_UPDATE_TRAFFIC_FAIL'
export const FEATURE_FLAG_UPDATE_TRAFFIC_RESET = 'FEATURE_FLAG_UPDATE_TRAFFIC_RESET'
