export const FEATURE_FLAGS_LIST_REQUEST = 'FEATURE_FLAGS_LIST_REQUEST'
export const FEATURE_FLAGS_LIST_SUCCESS = 'FEATURE_FLAGS_LIST_SUCCESS'
export const FEATURE_FLAGS_LIST_FAIL = 'FEATURE_FLAGS_LIST_FAIL'
